-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Treasury
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Treasury
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Treasury` DEFAULT CHARACTER SET utf8 ;
USE `Treasury` ;

-- -----------------------------------------------------
-- Table `Treasury`.`ACCOUNT_MASTER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treasury`.`ACCOUNT_MASTER` (
  `ACCT_KEY` VARCHAR(38) NOT NULL,
  `ACCT_NAME` VARCHAR(200) NOT NULL,
  `ACCT_PARENT` VARCHAR(45) NULL DEFAULT NULL,
  `SOURCE_KEY` VARCHAR(64) NULL DEFAULT NULL,
  `REPORTED_FLAG` INT(11) NOT NULL DEFAULT '0',
  `ROLLUP_FLAG` INT(11) NOT NULL DEFAULT '0',
  `DISPLAY_ORDER` INT(11) NOT NULL DEFAULT '0',
  `EXTERNAL_FLAG` INT(11) NOT NULL DEFAULT '0',
  `CLOSED_FLAG` INT(11) NOT NULL DEFAULT '0',
  `ORG` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`ACCT_KEY`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Treasury`.`BANK_DATA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treasury`.`BANK_DATA` (
  `ID` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `UPLOAD_BATCH` VARCHAR(40) NOT NULL,
  `RECORD_HASH` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `TRANS_DATE` DATE NOT NULL,
  `TRANS_VALUE` DOUBLE(11,2) NOT NULL,
  `CAT_NUM` INT(11) NULL DEFAULT NULL,
  `CAT_NAME` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `REF_NUM` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `DESC` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `CODE` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `IDENTIFIER` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `IDX_BATCH` USING BTREE (`UPLOAD_BATCH`) VISIBLE,
  INDEX `IDX_TRANS_DATE` USING BTREE (`TRANS_DATE`) VISIBLE,
  INDEX `IDX_REF` USING BTREE (`REF_NUM`) VISIBLE,
  INDEX `IDX_IDEN` USING BTREE (`IDENTIFIER`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Treasury`.`BANK_DATA_ARCHIVE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treasury`.`BANK_DATA_ARCHIVE` (
  `ID` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `UPLOAD_BATCH` VARCHAR(40) NOT NULL,
  `RECORD_HASH` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `TRANS_DATE` DATE NOT NULL,
  `TRANS_VALUE` DOUBLE(11,2) NOT NULL,
  `CAT_NUM` INT(11) NULL DEFAULT NULL,
  `CAT_NAME` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `REF_NUM` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `DESC` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `CODE` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `IDENTIFIER` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `IDX_BATCH` USING BTREE (`UPLOAD_BATCH`) VISIBLE,
  INDEX `IDX_TRANS_DATE` USING BTREE (`TRANS_DATE`) VISIBLE,
  INDEX `IDX_REF` USING BTREE (`REF_NUM`) VISIBLE,
  INDEX `IDX_IDEN` USING BTREE (`IDENTIFIER`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Treasury`.`CODE_SET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treasury`.`CODE_SET` (
  `KEY` INT(11) NOT NULL AUTO_INCREMENT,
  `CODE_SYS` VARCHAR(50) NOT NULL,
  `CODE_VAL` VARCHAR(50) NOT NULL,
  `CONFIG` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`KEY`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Treasury`.`DEPOSITS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treasury`.`DEPOSITS` (
  `DEPOSIT_KEY` VARCHAR(40) NOT NULL,
  `DEPOSIT_DATE` DATE NOT NULL,
  `DEPOSIT_TOTAL` DOUBLE(11,2) NOT NULL,
  `FINALIZED` INT(11) NOT NULL DEFAULT '0',
  `FINALIZED_DATE` DATE NULL DEFAULT '9999-12-31',
  `RECONCILED` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`DEPOSIT_KEY`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Treasury`.`FUNDS_REGISTER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treasury`.`FUNDS_REGISTER` (
  `FUNDS_KEY` VARCHAR(40) NOT NULL,
  `FUNDS_DATE` DATE NOT NULL,
  `AMOUNT` DOUBLE(11,2) NOT NULL,
  `METHOD` INT(11) NOT NULL DEFAULT '0',
  `REF_VALUE` VARCHAR(100) NULL DEFAULT NULL,
  `COMMENTS` VARCHAR(500) NULL DEFAULT NULL,
  `WHO` VARCHAR(200) NULL DEFAULT NULL,
  `WHAT` VARCHAR(200) NULL DEFAULT NULL,
  `DEPOSIT_KEY` VARCHAR(40) NULL DEFAULT NULL,
  `RECONCILED` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`FUNDS_KEY`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `Treasury`.`ITEM_ASSOCIATIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treasury`.`ITEM_ASSOCIATIONS` (
  `SOURCE_KEY` VARCHAR(40) NOT NULL,
  `TARGET_TYPE` INT(11) NOT NULL,
  `TARGET_KEY` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`SOURCE_KEY`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Treasury`.`PAYMENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treasury`.`PAYMENTS` (
  `PAYMENT_KEY` VARCHAR(40) NOT NULL,
  `PAYMENT_DATE` DATE NOT NULL,
  `AMOUNT` DOUBLE(11,2) NOT NULL,
  `METHOD` INT(11) NOT NULL DEFAULT '0',
  `REF_VALUE` VARCHAR(100) NULL DEFAULT NULL,
  `COMMENTS` VARCHAR(500) NULL DEFAULT NULL,
  `FINALIZED` INT(11) NOT NULL DEFAULT '0',
  `FINALIZED_DATE` DATE NOT NULL DEFAULT '9999-12-31',
  `RECONCILED` INT(11) NOT NULL DEFAULT '0',
  `WHO` VARCHAR(200) NULL DEFAULT NULL,
  `WHAT` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`PAYMENT_KEY`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Treasury`.`TROOP_TRACK_DATA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treasury`.`TROOP_TRACK_DATA` (
  `ID` VARCHAR(40) NOT NULL,
  `UPLOAD_BATCH` VARCHAR(40) NOT NULL,
  `RECORD_HASH` VARCHAR(64) NOT NULL,
  `ACCT_HASH` VARCHAR(64) NOT NULL,
  `ACCT_NAME` VARCHAR(200) NOT NULL,
  `ACTIVITY_DATE` DATE NOT NULL,
  `ACTIVITY_VALUE` DOUBLE(11,2) NOT NULL,
  `MEMO` MEDIUMTEXT NULL DEFAULT NULL,
  `PAYEE` VARCHAR(200) NULL DEFAULT NULL,
  `DESCRIPTION` MEDIUMTEXT NULL DEFAULT NULL,
  `CATEGORIES` VARCHAR(200) NULL DEFAULT NULL,
  `CHECK_NUM` VARCHAR(50) NULL DEFAULT NULL,
  `TENDER_TYPE` VARCHAR(100) NULL DEFAULT NULL,
  `TENDER_HASH` VARCHAR(64) NULL DEFAULT NULL COMMENT '	',
  `DETAILS` MEDIUMTEXT NULL DEFAULT NULL,
  `BALANCE` DOUBLE(11,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`ID`),
  INDEX `IDX_ACCT_HASH` USING BTREE (`ACCT_HASH`) VISIBLE,
  INDEX `IDX_ACCT_NAME` (`ACCT_NAME` ASC) VISIBLE,
  INDEX `IDX_RECORD_HASH` USING BTREE (`RECORD_HASH`) VISIBLE,
  INDEX `IDX_BATCH` USING BTREE (`UPLOAD_BATCH`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Treasury`.`TROOP_TRACK_DATA_ARCHIVE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Treasury`.`TROOP_TRACK_DATA_ARCHIVE` (
  `ID` VARCHAR(40) NOT NULL,
  `UPLOAD_BATCH` VARCHAR(40) NOT NULL,
  `RECORD_HASH` VARCHAR(64) NOT NULL,
  `ACCT_HASH` VARCHAR(64) NOT NULL,
  `ACCT_NAME` VARCHAR(200) NOT NULL,
  `ACTIVITY_DATE` DATE NOT NULL,
  `ACTIVITY_VALUE` DOUBLE(11,2) NOT NULL,
  `MEMO` MEDIUMTEXT NULL DEFAULT NULL,
  `PAYEE` VARCHAR(200) NULL DEFAULT NULL,
  `DESCRIPTION` MEDIUMTEXT NULL DEFAULT NULL,
  `CATEGORIES` VARCHAR(200) NULL DEFAULT NULL,
  `CHECK_NUM` VARCHAR(50) NULL DEFAULT NULL,
  `TENDER_TYPE` VARCHAR(100) NULL DEFAULT NULL,
  `TENDER_HASH` VARCHAR(64) NULL DEFAULT NULL COMMENT '	',
  `DETAILS` MEDIUMTEXT NULL DEFAULT NULL,
  `BALANCE` DOUBLE(11,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`ID`),
  INDEX `IDX_ACCT_HASH` USING BTREE (`ACCT_HASH`) VISIBLE,
  INDEX `IDX_ACCT_NAME` (`ACCT_NAME` ASC) VISIBLE,
  INDEX `IDX_RECORD_HASH` USING BTREE (`RECORD_HASH`) VISIBLE,
  INDEX `IDX_BATCH` USING BTREE (`UPLOAD_BATCH`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- View `Treasury`.`BANK_TRANSACTION_JOURNAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Treasury`.`BANK_TRANSACTION_JOURNAL`;
USE `Treasury`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `Treasury`.`BANK_TRANSACTION_JOURNAL` AS select `BD`.`ID` AS `ID`,`BD`.`UPLOAD_BATCH` AS `UPLOAD_BATCH`,`BD`.`RECORD_HASH` AS `RECORD_HASH`,`BD`.`TRANS_DATE` AS `TRANS_DATE`,`BD`.`TRANS_VALUE` AS `TRANS_VALUE`,`BD`.`CAT_NUM` AS `CAT_NUM`,`BD`.`CAT_NAME` AS `CAT_NAME`,`BD`.`REF_NUM` AS `REF_NUM`,`BD`.`DESC` AS `DESC`,`BD`.`CODE` AS `CODE`,`BD`.`IDENTIFIER` AS `IDENTIFIER` from `Treasury`.`BANK_DATA` `BD` union all select `BDA`.`ID` AS `ID`,`BDA`.`UPLOAD_BATCH` AS `UPLOAD_BATCH`,`BDA`.`RECORD_HASH` AS `RECORD_HASH`,`BDA`.`TRANS_DATE` AS `TRANS_DATE`,`BDA`.`TRANS_VALUE` AS `TRANS_VALUE`,`BDA`.`CAT_NUM` AS `CAT_NUM`,`BDA`.`CAT_NAME` AS `CAT_NAME`,`BDA`.`REF_NUM` AS `REF_NUM`,`BDA`.`DESC` AS `DESC`,`BDA`.`CODE` AS `CODE`,`BDA`.`IDENTIFIER` AS `IDENTIFIER` from `Treasury`.`BANK_DATA_ARCHIVE` `BDA`;

-- -----------------------------------------------------
-- View `Treasury`.`TROOP_TRACK_JOURNAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Treasury`.`TROOP_TRACK_JOURNAL`;
USE `Treasury`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `Treasury`.`TROOP_TRACK_JOURNAL` AS select `Treasury`.`TROOP_TRACK_DATA`.`ID` AS `ID`,`Treasury`.`TROOP_TRACK_DATA`.`UPLOAD_BATCH` AS `UPLOAD_BATCH`,`Treasury`.`TROOP_TRACK_DATA`.`RECORD_HASH` AS `RECORD_HASH`,`Treasury`.`TROOP_TRACK_DATA`.`ACCT_HASH` AS `ACCT_HASH`,`Treasury`.`TROOP_TRACK_DATA`.`ACCT_NAME` AS `ACCT_NAME`,`Treasury`.`TROOP_TRACK_DATA`.`ACTIVITY_DATE` AS `ACTIVITY_DATE`,`Treasury`.`TROOP_TRACK_DATA`.`ACTIVITY_VALUE` AS `ACTIVITY_VALUE`,`Treasury`.`TROOP_TRACK_DATA`.`MEMO` AS `MEMO`,`Treasury`.`TROOP_TRACK_DATA`.`PAYEE` AS `PAYEE`,`Treasury`.`TROOP_TRACK_DATA`.`DESCRIPTION` AS `DESCRIPTION`,`Treasury`.`TROOP_TRACK_DATA`.`CATEGORIES` AS `CATEGORIES`,`Treasury`.`TROOP_TRACK_DATA`.`CHECK_NUM` AS `CHECK_NUM`,`Treasury`.`TROOP_TRACK_DATA`.`TENDER_TYPE` AS `TENDER_TYPE`,`Treasury`.`TROOP_TRACK_DATA`.`TENDER_HASH` AS `TENDER_HASH`,`Treasury`.`TROOP_TRACK_DATA`.`DETAILS` AS `DETAILS`,`Treasury`.`TROOP_TRACK_DATA`.`BALANCE` AS `BALANCE` from `Treasury`.`TROOP_TRACK_DATA` union all select `Treasury`.`TROOP_TRACK_DATA_ARCHIVE`.`ID` AS `ID`,`Treasury`.`TROOP_TRACK_DATA_ARCHIVE`.`UPLOAD_BATCH` AS `UPLOAD_BATCH`,`Treasury`.`TROOP_TRACK_DATA_ARCHIVE`.`RECORD_HASH` AS `RECORD_HASH`,`Treasury`.`TROOP_TRACK_DATA_ARCHIVE`.`ACCT_HASH` AS `ACCT_HASH`,`Treasury`.`TROOP_TRACK_DATA_ARCHIVE`.`ACCT_NAME` AS `ACCT_NAME`,`Treasury`.`TROOP_TRACK_DATA_ARCHIVE`.`ACTIVITY_DATE` AS `ACTIVITY_DATE`,`Treasury`.`TROOP_TRACK_DATA_ARCHIVE`.`ACTIVITY_VALUE` AS `ACTIVITY_VALUE`,`Treasury`.`TROOP_TRACK_DATA_ARCHIVE`.`MEMO` AS `MEMO`,`Treasury`.`TROOP_TRACK_DATA_ARCHIVE`.`PAYEE` AS `PAYEE`,`Treasury`.`TROOP_TRACK_DATA_ARCHIVE`.`DESCRIPTION` AS `DESCRIPTION`,`Treasury`.`TROOP_TRACK_DATA_ARCHIVE`.`CATEGORIES` AS `CATEGORIES`,`Treasury`.`TROOP_TRACK_DATA_ARCHIVE`.`CHECK_NUM` AS `CHECK_NUM`,`Treasury`.`TROOP_TRACK_DATA_ARCHIVE`.`TENDER_TYPE` AS `TENDER_TYPE`,`Treasury`.`TROOP_TRACK_DATA_ARCHIVE`.`TENDER_HASH` AS `TENDER_HASH`,`Treasury`.`TROOP_TRACK_DATA_ARCHIVE`.`DETAILS` AS `DETAILS`,`Treasury`.`TROOP_TRACK_DATA_ARCHIVE`.`BALANCE` AS `BALANCE` from `Treasury`.`TROOP_TRACK_DATA_ARCHIVE`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
