CREATE TABLE IF NOT EXISTS `ACCOUNT_MASTER` (
`ACCT_KEY` VARCHAR(38) NOT NULL,
`ACCT_NAME` VARCHAR(200) NOT NULL,
`ACCT_PARENT` VARCHAR(45) NULL DEFAULT NULL,
`SOURCE_KEY` VARCHAR(64) NULL DEFAULT NULL,
`REPORTED_FLAG` INT(11) NOT NULL DEFAULT '0',
`ROLLUP_FLAG` INT(11) NOT NULL DEFAULT '0',
`DISPLAY_ORDER` INT(11) NOT NULL DEFAULT '0',
`EXTERNAL_FLAG` INT(11) NOT NULL DEFAULT '0',
`CLOSED_FLAG` INT(11) NOT NULL DEFAULT '0',
`ORG` VARCHAR(10) NULL DEFAULT NULL,
PRIMARY KEY (`ACCT_KEY`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;