CREATE TABLE IF NOT EXISTS `BANK_DATA` (
`ID` VARCHAR(40) NOT NULL,
`UPLOAD_BATCH` VARCHAR(40) NOT NULL,
`RECORD_HASH` VARCHAR(64) NOT NULL,
`TRANS_DATE` DATE NOT NULL,
`TRANS_VALUE` DOUBLE(11,2) NOT NULL,
`CAT_NUM` INT(11) NULL DEFAULT NULL,
`CAT_NAME` VARCHAR(100) NULL DEFAULT NULL,
`REF_NUM` VARCHAR(100) NULL DEFAULT NULL,
`DESC` VARCHAR(100) NULL DEFAULT NULL,
`CODE` VARCHAR(100) NULL DEFAULT NULL,
`IDENTIFIER` VARCHAR(50) NULL DEFAULT NULL,
PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `BANK_DATA` ADD INDEX `IDX_BANK_BATCH` USING BTREE (`UPLOAD_BATCH`);
ALTER TABLE `BANK_DATA` ADD INDEX `IDX_BANK_TRANS_DATE` USING BTREE (`TRANS_DATE`);
ALTER TABLE `BANK_DATA` ADD INDEX `IDX_BANK_REF` USING BTREE (`REF_NUM`);
ALTER TABLE `BANK_DATA` ADD INDEX `IDX_BANK_IDEN` USING BTREE (`IDENTIFIER`);
