CREATE TABLE IF NOT EXISTS `FUNDS_REGISTER` (
`FUNDS_KEY` VARCHAR(40) NOT NULL,
`FUNDS_DATE` DATE NOT NULL,
`AMOUNT` DOUBLE(11,2) NOT NULL,
`METHOD` INT(11) NOT NULL DEFAULT '0',
`REF_VALUE` VARCHAR(100) NULL DEFAULT NULL,
`COMMENTS` VARCHAR(500) NULL DEFAULT NULL,
`WHO` VARCHAR(200) NULL DEFAULT NULL,
`WHAT` VARCHAR(200) NULL DEFAULT NULL,
`DEPOSIT_KEY` VARCHAR(40) NULL DEFAULT NULL,
`RECONCILED` INT(11) NOT NULL DEFAULT '0',
PRIMARY KEY (`FUNDS_KEY`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;