CREATE TABLE IF NOT EXISTS `PAYMENTS` (
`PAYMENT_KEY` VARCHAR(40) NOT NULL,
`PAYMENT_DATE` DATE NOT NULL,
`AMOUNT` DOUBLE(11,2) NOT NULL,
`METHOD` INT(11) NOT NULL DEFAULT '0',
`REF_VALUE` VARCHAR(100) NULL DEFAULT NULL,
`COMMENTS` VARCHAR(500) NULL DEFAULT NULL,
`FINALIZED` INT(11) NOT NULL DEFAULT '0',
`FINALIZED_DATE` DATE NOT NULL DEFAULT '9999-12-31',
`RECONCILED` INT(11) NOT NULL DEFAULT '0',
`WHO` VARCHAR(200) NULL DEFAULT NULL,
`WHAT` VARCHAR(200) NULL DEFAULT NULL,
PRIMARY KEY (`PAYMENT_KEY`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;