CREATE TABLE IF NOT EXISTS `TROOP_TRANSACTIONS_ARCHIVE` (
`ID` VARCHAR(40) NOT NULL,
`UPLOAD_BATCH` VARCHAR(40) NOT NULL,
`RECORD_HASH` VARCHAR(64) NOT NULL,
`ACCT_HASH` VARCHAR(64) NOT NULL,
`ACCT_NAME` VARCHAR(200) NOT NULL,
`ACTIVITY_DATE` DATE NOT NULL,
`ACTIVITY_VALUE` DOUBLE(11,2) NOT NULL,
`MEMO` MEDIUMTEXT NULL DEFAULT NULL,
`PAYEE` VARCHAR(200) NULL DEFAULT NULL,
`DESCRIPTION` MEDIUMTEXT NULL DEFAULT NULL,
`CATEGORIES` VARCHAR(200) NULL DEFAULT NULL,
`CHECK_NUM` VARCHAR(50) NULL DEFAULT NULL,
`TENDER_TYPE` VARCHAR(100) NULL DEFAULT NULL,
`TENDER_HASH` VARCHAR(64) NULL DEFAULT NULL COMMENT '	',
`DETAILS` MEDIUMTEXT NULL DEFAULT NULL,
`BALANCE` DOUBLE(11,2) NOT NULL DEFAULT '0.00',
PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `TROOP_TRANSACTIONS_ARCHIVE` ADD INDEX `IDX_TTRANS_ARCH_ACCT_HASH` USING BTREE (`ACCT_HASH`);
ALTER TABLE `TROOP_TRANSACTIONS_ARCHIVE` ADD INDEX `IDX_TTRANS_ARCH_ACCT_NAME` USING BTREE (`ACCT_NAME`);
ALTER TABLE `TROOP_TRANSACTIONS_ARCHIVE` ADD INDEX `IDX_TTRANS_ARCH_REC_HASH` USING BTREE (`RECORD_HASH`);
ALTER TABLE `TROOP_TRANSACTIONS_ARCHIVE` ADD INDEX `IDX_TTRANS_ARCH_BATCH` USING BTREE (`UPLOAD_BATCH`);
